_RESOURCE_INFO = [
    (0, 0x0, "error", "error", ".NONE", "", "empty_resource_handler"),
    (1, 0x1, "descriptor", "descriptors", ".DESC", "DESC\\", "mashable_resource_handler<class_level_descriptor_set>"),
    (2, 0x2, "sin", "sins", ".SIN", "SIN\\", "mashable_resource_handler<class_sin_container>"),
    (3, 0x3, "textfile", "textfiles", ".TXT", "TXT\\", "mashable_resource_handler<struct_text_resource>"),
    (4, 0x4, "terrain_types", "terrain_typeses", ".CSV", "CSV\\", "mashable_resource_handler<struct_terrain_types_set>"),
    (5, 0x5, "language", "languages", ".LANG", "LANG\\", "mashable_resource_handler<class_localized_string_table>"),
    (6, 0x6, "district_graph", "district_graphs", ".DSG", "DSG\\", "mashable_resource_handler<class_district_graph_container>"),
    (7, 0x7, "speedtree_coll", "speedtree_colls", ".STC", "STC\\", "mashable_resource_handler<class_speedtree_collection>"),
    (8, 0x8, "speedtree_coll_refs", "speedtree_coll_refss", ".PCSTCR", "PCSTCR\\", "mashable_resource_handler<class_speedtree_collection_reference>"),
    (9, 0x9, "script", "scripts", ".PCSX", "PCSX\\", "mashable_resource_handler<class_script_executable>"),
    (10, 0xa, "script_gv", "script_gvs", ".PCGV", "PCGV\\", "mashable_resource_handler<class_script_var_container>"),
    (11, 0xb, "script_sv", "script_svs", ".PCSV", "PCSV\\", "mashable_resource_handler<class_script_var_container>"),
    (12, 0xc, "GenBlockMap", "GenBlockMaps", ".GBMAP", "GBMAP\\", "mashable_resource_handler<class_gb_map>"),
    (13, 0xd, "traffic_light_info", "traffic_light_infos", ".TRAF_LT_INFPC", "TRAF_LT_INFPC\\",
     "mashable_resource_handler<class_region_traffic_light_info>"),
    (14, 0xe, "texture", "textures", ".PCTEXTURE", "PCTEXTURE\\", "merged_singular_apk_resource_handler"),
    (15, 0xf, "fxbinary", "fxbinaries", ".PCFX", "PCFX\\", "merged_singular_apk_resource_handler"),
    (16, 0x10, "material", "materials", ".PCMATERIAL", "PCMATERIAL\\", "merged_singular_apk_resource_handler"),
    (17, 0x11, "mesh", "meshes", ".PCMESH", "PCMESH\\", "merged_singular_apk_resource_handler"),
    (18, 0x12, "ngl_skeleton", "ngl_skeletons", ".PCNGLSKELETON", "PCNGLSKELETON\\",
     "merged_singular_apk_resource_handler"),
    (19, 0x13, "nal_skeleton", "nal_skeletons", ".PCSKEL", "PCSKEL\\", "merged_singular_apk_resource_handler"),
    (20, 0x14, "ngl_font", "ngl_fonts", ".PCFONT", "PCFONT\\", "merged_singular_apk_resource_handler"),
    (21, 0x15, "animation", "animations", ".PCANIM", "PCANIM\\", "merged_singular_apk_resource_handler"),
    (22, 0x16, "scene_animation", "scene_animations", ".PCSANIM", "PCSANIM\\", "merged_singular_apk_resource_handler"),
    (23, 0x17, "morph", "morphs", ".PCMORPH", "PCMORPH\\", "merged_singular_apk_resource_handler"),
    (24, 0x18, "efx", "efxs", ".PCEFXB", "PCEFXB\\", "merged_singular_apk_resource_handler"),
    (25, 0x19, "merged_apk", "merged_apks", ".PCAPK", "PCAPK\\", "merged_apk_resource_handler"),
    (26, 0x1a, "nal_skeleton_map", "nal_skeleton_maps", ".SKELMAP", "SKELMAP\\", "singular_apk_resource_handler"),
    (27, 0x1b, "convex_hull_mesh", "convex_hull_meshes", ".PCCVX", "PCCVX\\", "singular_apk_resource_handler"),
    (28, 0x1c, "vehicle_model_depot", "vehicle_model_depots", ".VDEPOT", "VDEPOT\\", "mashable_resource_handler<class_vehicle_model_depot>"),
    (29, 0x1d, "TILEMAP", "TILEMAPs", ".TILEMAP", "TILEMAP\\", "mashable_resource_handler<class_Tilemap>"),
    (30, 0x1e, "ENVIRONMENT", "ENVIRONMENTs", ".ENVIRONMENT", "ENVIRONMENT\\", "mashable_resource_handler<class_Environment>"),
    (31, 0x1f, "LIGHTBEHAVIOR", "LIGHTBEHAVIORs", ".LIGHTBEHAVIOR", "LIGHTBEHAVIOR\\", "mashable_resource_handler<class_LightBehavior>"),
    (32, 0x20, "GRAPHICSOPTIONS", "GRAPHICSOPTIONSs", ".GRAPHICSOPTIONS", "GRAPHICSOPTIONS\\",
     "mashable_resource_handler<class_GraphicsOptions>"),
    (33, 0x21, "EFFECTCONTAINER", "EFFECTCONTAINERs", ".EFFECTCONTAINER", "EFFECTCONTAINER\\",
     "mashable_resource_handler<class_EffectContainer>"),
    (34, 0x22, "SMDECALMATERIAL", "SMDECALMATERIALs", ".SMDECALMATERIAL", "SMDECALMATERIAL\\",
     "mashable_resource_handler<class_SMDecalMaterial>"),
    (35, 0x23, "PHATPALETTE", "PHATPALETTEs", ".PHATPALETTE", "PHATPALETTE\\", "mashable_resource_handler<class_PhatPalette>"),
    (36, 0x24, "COWBELL", "COWBELLs", ".COWBELL", "COWBELL\\", "mashable_resource_handler<class_CowbellFile>"),
    (37, 0x25, "MESHMAP", "MESHMAPs", ".MESHMAP", "MESHMAP\\", "mashable_resource_handler<class_Meshmap>"),
    (38, 0x26, "CLOUDTWEAK", "CLOUDTWEAKs", ".CLOUDTWEAK", "CLOUDTWEAK\\", "mashable_resource_handler<class_CloudTweak>"),
    (39, 0x27, "CITYLODS", "CITYLODSs", ".CITYLODS", "CITYLODS\\", "mashable_resource_handler<class_CityLODs>"),
    (40, 0x28, "SMROADPARAM", "SMROADPARAMs", ".SMROADPARAM", "SMROADPARAM\\", "mashable_resource_handler<class_SMRoadParam>"),
    (41, 0x29, "ALLBUILDINGS", "ALLBUILDINGSs", ".ALLBUILDINGS", "ALLBUILDINGS\\", "mashable_resource_handler<class_AllBuildings>"),
    (42, 0x2a, "UIP3DW", "UIP3DWs", ".UIP3DW", "UIP3DW\\", "mashable_resource_handler<class_IGO3DWidgetParameters>"),
    (43, 0x2b, "UIP3DT", "UIP3DTs", ".UIP3DT", "UIP3DT\\", "mashable_resource_handler<class_IGO3DTextParameters>"),
    (44, 0x2c, "SMDECALPARAM", "SMDECALPARAMs", ".SMDECALPARAM", "SMDECALPARAM\\", "mashable_resource_handler<class_SMDecalParam>"),
    (45, 0x2d, "ADJUSTMENTLAYERSLIBRARY", "ADJUSTMENTLAYERSLIBRARYs", ".ADJUSTMENTLAYERSLIBRARY",
     "ADJUSTMENTLAYERSLIBRARY\\", "mashable_resource_handler<class_AdjustmentLayersLibrary>"),
    (46, 0x2e, "OUTDOORS", "OUTDOORSs", ".OUTDOORS", "OUTDOORS\\", "mashable_resource_handler<class_Outdoors>"),
    (47, 0x2f, "DAYSKYCOLOR", "DAYSKYCOLORs", ".DAYSKYCOLOR", "DAYSKYCOLOR\\", "mashable_resource_handler<class_daySkyColor>"),
    (48, 0x30, "NIGHTSKYCOLOR", "NIGHTSKYCOLORs", ".NIGHTSKYCOLOR", "NIGHTSKYCOLOR\\", "mashable_resource_handler<class_nightSkyColor>"),
    (49, 0x31, "PRELIGHT", "PRELIGHTs", ".PRELIGHT", "PRELIGHT\\", "mashable_resource_handler<class_PreLight>"),
    (50, 0x32, "SMBUILDINGLODPARAM", "SMBUILDINGLODPARAMs", ".SMBUILDINGLODPARAM", "SMBUILDINGLODPARAM\\",
     "mashable_resource_handler<class_SMBuildingLODParam>"),
    (51, 0x33, "SMROADLODPARAM", "SMROADLODPARAMs", ".SMROADLODPARAM", "SMROADLODPARAM\\", "mashable_resource_handler<class_SMRoadLODParam>"),
    (52, 0x34, "SMRETROFITPARAM", "SMRETROFITPARAMs", ".SMRETROFITPARAM", "SMRETROFITPARAM\\",
     "mashable_resource_handler<class_SMRetrofitParam>"),
    (53, 0x35, "JSON_REGIONINFO", "JSON_REGIONINFOs", ".JSON_REGIONINFO", "JSON_REGIONINFO\\",
     "mashable_resource_handler<class_region_spawn_interface>"),
    (54, 0x36, "JSON_METERDATA", "JSON_METERDATAs", ".JSON_METERDATA", "JSON_METERDATA\\", "mashable_resource_handler<class_meter_data_file>"),
    (55, 0x37, "JSON_METERBEHAVIOR", "JSON_METERBEHAVIORs", ".JSON_METERBEHAVIOR", "JSON_METERBEHAVIOR\\",
     "mashable_resource_handler<class_meter_behavior_file>"),
    (56, 0x38, "JSON_COMBOMOVEINFO", "JSON_COMBOMOVEINFOs", ".JSON_COMBOMOVEINFO", "JSON_COMBOMOVEINFO\\",
     "mashable_resource_handler<class_combo_move_type_file>"),
    (57, 0x39, "JSON_QUESTDESC", "JSON_QUESTDESCs", ".JSON_QUESTDESC", "JSON_QUESTDESC\\", "mashable_resource_handler<class_quest_descriptions>"),
    (58, 0x3a, "JSON_QUESTLIST", "JSON_QUESTLISTs", ".JSON_QUESTLIST", "JSON_QUESTLIST\\", "mashable_resource_handler<class_quest_list>"),
    (59, 0x3b, "JSON_CONVERSATION", "JSON_CONVERSATIONs", ".JSON_CONVERSATION", "JSON_CONVERSATION\\",
     "mashable_resource_handler<class_conversation>"),
    (60, 0x3c, "JSON_SPAWNTABLE", "JSON_SPAWNTABLEs", ".JSON_SPAWNTABLE", "JSON_SPAWNTABLE\\",
     "mashable_resource_handler<class_spawn_table_interface>"),
    (61, 0x3d, "JSON_SPAWNPROGRESSION", "JSON_SPAWNPROGRESSIONs", ".JSON_SPAWNPROGRESSION", "JSON_SPAWNPROGRESSION\\",
     "mashable_resource_handler<class_spawn_item_collection>"),
    (62, 0x3e, "JSON_SPAWNPOINTS", "JSON_SPAWNPOINTSs", ".JSON_SPAWNPOINTS", "JSON_SPAWNPOINTS\\",
     "mashable_resource_handler<class_spawn_point_list_collection>"),
    (63, 0x3f, "JSON_NEIGHBORHOODINFO", "JSON_NEIGHBORHOODINFOs", ".JSON_NEIGHBORHOODINFO", "JSON_NEIGHBORHOODINFO\\",
     "mashable_resource_handler<class_neighborhood_interface>"),
    (64, 0x40, "JSON_DEF_VALUES", "JSON_DEF_VALUESs", ".JSON_DEF_VALUES", "JSON_DEF_VALUES\\",
     "mashable_resource_handler<class_default_values>"),
    (65, 0x41, "JSON_PROGRESSMESSAGES", "JSON_PROGRESSMESSAGESs", ".JSON_PROGRESSMESSAGES", "JSON_PROGRESSMESSAGES\\",
     "mashable_resource_handler<class_progression_messages>"),
    (66, 0x42, "JSON_SPAWNITEMS", "JSON_SPAWNITEMSs", ".JSON_SPAWNITEMS", "JSON_SPAWNITEMS\\",
     "mashable_resource_handler<class_static_spawn_item_collection>"),
    (67, 0x43, "JSON_UPGRADES", "JSON_UPGRADESs", ".JSON_UPGRADES", "JSON_UPGRADES\\", "mashable_resource_handler<class_rpg_upgrades>"),
    (68, 0x44, "JSON_SOUNDMAP", "JSON_SOUNDMAPs", ".JSON_SOUNDMAP", "JSON_SOUNDMAP\\", "mashable_resource_handler<class_sound_map>"),
    (69, 0x45, "JSON_UICHARINFO", "JSON_UICHARINFOs", ".JSON_UICHARINFO", "JSON_UICHARINFO\\",
     "mashable_resource_handler<class_ui_character_info_list>"),
    (70, 0x46, "JSON_SUMMONPROGRESSION", "JSON_SUMMONPROGRESSIONs", ".JSON_SUMMONPROGRESSION",
     "JSON_SUMMONPROGRESSION\\", "mashable_resource_handler<class_summon_progression>"),
    (71, 0x47, "JSON_ENVIRONMENTPROGRESSION", "JSON_ENVIRONMENTPROGRESSIONs", ".JSON_ENVIRONMENTPROGRESSION",
     "JSON_ENVIRONMENTPROGRESSION\\", "mashable_resource_handler<class_environment_progression>"),
    (72, 0x48, "JSON_RENDERLOD", "JSON_RENDERLODs", ".JSON_RENDERLOD", "JSON_RENDERLOD\\", "mashable_resource_handler<class_render_lod_mgr>"),
    (73, 0x49, "viseme_stream", "viseme_streams", ".LIP", "LIP\\", "mashable_resource_handler<class_VisemeStream>"),
    (74, 0x4a, "static_colgeom", "static_colgeoms", ".SCGPC", "SCGPC\\", "mashable_resource_handler<class_static_colgeom_root>"),
    (75, 0x4b, "lego_map", "lego_maps", ".LEGO_MAPPC", "LEGO_MAPPC\\", "mashable_resource_handler<struct_lego_map_root_node>"),
    (76, 0x4c, "scn_quad_path", "scn_quad_paths", ".QP", "QP\\", "mashable_resource_handler<class_ai_pf_region_graph>"),
    (77, 0x4d, "path", "path", ".PATH", "PATH\\", "mashable_resource_handler<class_path_graph>"),
    (78, 0x4e, "scn_env_box", "scn_env_boxes", ".EB", "EB\\", "mashable_resource_handler<class_environment_box_set>"),
    (79, 0x4f, "cosmetic_environ", "cosmetic_environs", ".CE", "CE\\", "mashable_resource_handler<class_cosmetic_environments_set>"),
    (80, 0x50, "sm3_light", "sm3_lights", ".SM3_LIGHTPC", "SM3_LIGHTPC\\", "mashable_resource_handler<class_sm3_light>"),
    (81, 0x51, "stall", "stalls", ".STALL", "STALL\\", "stall_resource_handler"),
    (82, 0x52, "slim", "slims", ".SLIM", "SLIM\\", "empty_resource_handler"),
    (83, 0x53, "slim_list", "slim_lists", ".SLIMLIST", "SLIMLIST\\", "slim_list_handler"),
    (84, 0x54, "als_file", "als_files", ".ALS", "ALS\\", "mashable_resource_handler<class_als::animation_logic_system_shared>"),
    (85, 0x55, "ai_state_graph", "ai_state_graphs", ".ASG", "ASG\\", "mashable_resource_handler<class_state_graph>"),
    (86, 0x56, "base_ai", "base_ais", ".BAI", "BAI\\", "mashable_resource_handler<class_core_ai_resource>"),
    (87, 0x57, "scn_audio_box", "scn_audio_boxes", ".AB", "AB\\", "mashable_resource_handler<class_region_audio_box_set>"),
    (88, 0x58, "box_trigger_info", "box_trigger_infos", ".BOX_TRIG_INFPC", "BOX_TRIG_INFPC\\",
     "box_trigger_resource_handler"),
    (89, 0x59, "scn_entity", "scn_entities", ".ENS", "ENS\\", "scene_entity_container_resource_handler"),
    (90, 0x5a, "anchor_coll", "anchor_colls", ".PCAC", "PCAC\\", "anchor_collection_resource_handler"),
    (91, 0x5b, "fx_cache", "fx_caches", ".FX_CACHE", "FX_CACHE\\", "mashable_resource_handler<class_fx_cache>"),
    (92, 0x5c, "entity", "entities", ".ENT", "ENT\\", "empty_resource_handler"),
    (93, 0x5d, "cut_scene", "cut_scenes", ".CUT", "CUT\\", "mashable_resource_handler<class_cut_scene>"),
    (94, 0x5e, "collision_mesh", "collision_meshes", ".COLL", "COLL\\", "empty_resource_handler"),
    (95, 0x5f, "packfile", "packfiles", ".PCPACK", "PCPACK\\", "empty_resource_handler"),
    (96, 0x60, "speedtree_spt", "speedtree_spts", ".SPT", "SPT\\", "empty_resource_handler"),
    (97, 0x61, "speedtree_seed", "speedtree_seeds", ".SEED", "SEED\\", "empty_resource_handler"),
    (98, 0x62, "speedtree_wind", "speedtree_winds", ".WIND", "WIND\\", "empty_resource_handler"),
    (99, 0x63, "sound_toc", "sound_tocs", ".pcstoc", "pcstoc\\", "mashable_resource_handler<class_sound_toc>"),
    (100, 0x64, "sound_index", "sound_indexs", ".sndids", "sndids\\", "mashable_resource_handler<class_sound_index>"),
    (101, 0x65, "ise_library", "ise_libraries", ".json_ise", "json_ise\\", "ise_library_handler"),
    (102, 0x66, "vertex_shader", "vertex_shaders", ".PCVS", "PCVS\\", "vertex_shader_handler"),
    (103, 0x67, "pixel_shader", "pixel_shaders", ".PCPS", "PCPS\\", "pixel_shader_handler")
]
RESOURCE_INFO = {id: ext for id, id_hex, desc, descp, ext, path, resource_handler_class in _RESOURCE_INFO}

RESOURCE_INFO_XE = dict(RESOURCE_INFO)
INFO_XE = {8: '.XESTCR', 9: '.XESX', 10: '.XEGV', 11: '.XESV', 13: '.TRAF_LT_INFXE', 14: '.XETEXTURE', 15: '.XEFX', 16: '.XEMATERIAL', 17: '.XEMESH', 18: '.XENGLSKELETON', 19: '.XESKEL', 20: '.XEFONT', 21: '.XEANIM', 22: '.XESANIM', 23: '.XEMORPH', 24: '.XEEFXB', 25: '.XEAPK', 27: '.XECVX', 74: '.SCGXE', 75: '.LEGO_MAPXE', 80: '.SM3_LIGHTXE', 88: '.BOX_TRIG_INFXE', 90: '.XEAC', 95: '.XEPACK', 102: '.XEVS', 103: '.XEPS'}
RESOURCE_INFO_XE.update(INFO_XE)

RESOURCE_INFO_PS3 = dict(RESOURCE_INFO)
INFO_PS3 = {8: '.PS3STCR', 9: '.PS3SX', 10: '.PS3GV', 11: '.PS3SV', 13: '.TRAF_LT_INFPS3', 14: '.PS3TEXTURE', 15: '.PS3FX', 16: '.PS3MATERIAL', 17: '.PS3MESH', 18: '.PS3NGLSKELETON', 19: '.PS3SKEL', 20: '.PS3FONT', 21: '.PS3ANIM', 22: '.PS3SANIM', 23: '.PS3MORPH', 24: '.PS3EFXB', 25: '.PS3APK', 27: '.PS3CVX', 74: '.SCGPS3', 75: '.LEGO_MAPPS3', 80: '.SM3_LIGHTPS3', 88: '.BOX_TRIG_INFPS3', 90: '.PS3AC', 95: '.PS3PACK', 102: '.PS3VS', 103: '.PS3PS'}
RESOURCE_INFO_PS3.update(INFO_PS3)

RESOURCE_INFO_PLATFORM = {'pc': RESOURCE_INFO, 'xe': RESOURCE_INFO_XE, 'ps3': RESOURCE_INFO_PS3}
